#!/bin/sh

# Flush all chains.
ip6tables -F INPUT
ip6tables -F FORWARD
ip6tables -F OUTPUT

# Set up default policies
ip6tables -P INPUT DROP
ip6tables -P FORWARD DROP
ip6tables -P OUTPUT DROP


# Allow everything from localhost
ip6tables -A INPUT -s ::1 -d ::1 -j ACCEPT

# Limit some types of ICMP
ip6tables -A INPUT -p icmpv6 --icmpv6-type router-advertisement -j ACCEPT
ip6tables -A INPUT -p icmpv6 --icmpv6-type destination-unreachable -j ACCEPT
ip6tables -A INPUT -p icmpv6 --icmpv6-type packet-too-big -j ACCEPT
ip6tables -A INPUT -p icmpv6 --icmpv6-type time-exceeded -j ACCEPT
ip6tables -A INPUT -p icmpv6 --icmpv6-type parameter-problem -j ACCEPT
ip6tables -A INPUT -p icmpv6 --icmpv6-type echo-request -m limit --limit 900/min -j ACCEPT

ip6tables -A FORWARD -p icmpv6 --icmpv6-type destination-unreachable -j ACCEPT
ip6tables -A FORWARD -p icmpv6 --icmpv6-type packet-too-big -j ACCEPT
ip6tables -A FORWARD -p icmpv6 --icmpv6-type time-exceeded -j ACCEPT
ip6tables -A FORWARD -p icmpv6 --icmpv6-type parameter-problem -j ACCEPT
ip6tables -A FORWARD -p icmpv6 --icmpv6-type echo-reply -m limit --limit 900/min -j ACCEPT
ip6tables -A FORWARD -p icmpv6 --icmpv6-type echo-request -m limit --limit 900/min -j ACCEPT

ip6tables -A OUPUT -o eth1 -p icmpv6 --icmpv6-type router-solicitation -j ACCEPT
ip6tables -A OUTPUT -o eth0 -p icmpv6 --icmpv6-type router-advertisement -j ACCEPT
ip6tables -A OUTPUT -p icmpv6 --icmpv6-type destination-unreachable -j ACCEPT
ip6tables -A OUTPUT -p icmpv6 --icmpv6-type packet-too-big -j ACCEPT
ip6tables -A OUTPUT-p icmpv6 --icmpv6-type time-exceeded -j ACCEPT
ip6tables -A OUTPUT -p icmpv6 --icmpv6-type parameter-problem -j ACCEPT
ip6tables -A OUTPUT -p icmpv6 --icmpv6-type echo-request -m limit --limit 900/min -j ACCEPT


# Allow local multicast
ip6tables -A INPUT -s ff00::/8 -j ACCEPT
ip6tables -A INPUT -d ff00::/8 -j ACCEPT

# Allow related and established connections.
ip6tables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

ip6tables -A FORWARD -o eth0 -m state --state NEW -j ACCEPT
ip6tables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT


# Allow in some ping
ip6tables -A INPUT -p ipv6-icmp -m limit --limit 500/sec -j ACCEPT

# Drop and log other packets. Limit logging to prevent flodding.
ip6tables -A INPUT -m limit -m state --state NEW,INVALID --limit 5/second -j LOG 




