#!/bin/sh

# Flush all chains.
ip6tables -F INPUT
ip6tables -F FORWARD
ip6tables -F OUTPUT

# Set up default policies
ip6tables -P INPUT DROP
ip6tables -P FORWARD DROP
ip6tables -P OUTPUT DROP


# Allow everything from localhost
ip6tables -A INPUT -s ::1 -d ::1 -j ACCEPT

# Limit some types of ICMP
ip6tables -A INPUT -i ! tun -p icmpv6 --icmpv6-type router-advertisement -j ACCEPT
ip6tables -A INPUT -p icmpv6 --icmpv6-type destination-unreachable -j ACCEPT
ip6tables -A INPUT -p icmpv6 --icmpv6-type packet-too-big -j ACCEPT
ip6tables -A INPUT -p icmpv6 --icmpv6-type time-exceeded -j ACCEPT
ip6tables -A INPUT -p icmpv6 --icmpv6-type parameter-problem -j ACCEPT
ip6tables -A INPUT -p icmpv6 --icmpv6-type echo-request -m limit --limit 900/min -j ACCEPT
ip6tables -A INPUT -p icmpv6 --icmpv6-type echo-reply -m limit --limit 900/min -j ACCEPT

ip6tables -A FORWARD -p icmpv6 --icmpv6-type destination-unreachable -j ACCEPT
ip6tables -A FORWARD -p icmpv6 --icmpv6-type packet-too-big -j ACCEPT
ip6tables -A FORWARD -p icmpv6 --icmpv6-type time-exceeded -j ACCEPT
ip6tables -A FORWARD -p icmpv6 --icmpv6-type parameter-problem -j ACCEPT
ip6tables -A FORWARD -p icmpv6 --icmpv6-type echo-reply -m limit --limit 900/min -j ACCEPT
ip6tables -A FORWARD -p icmpv6 --icmpv6-type echo-request -m limit --limit 900/min -j ACCEPT

ip6tables -A OUTPUT -o ! tun -p icmpv6 --icmpv6-type router-solicitation -j ACCEPT
ip6tables -A OUTPUT -o ! tun -p icmpv6 --icmpv6-type router-advertisement -j ACCEPT
ip6tables -A OUTPUT -p icmpv6 --icmpv6-type destination-unreachable -j ACCEPT
ip6tables -A OUTPUT -p icmpv6 --icmpv6-type packet-too-big -j ACCEPT
ip6tables -A OUTPUT -p icmpv6 --icmpv6-type time-exceeded -j ACCEPT
ip6tables -A OUTPUT -p icmpv6 --icmpv6-type parameter-problem -j ACCEPT
ip6tables -A OUTPUT -p icmpv6 --icmpv6-type echo-request -m limit --limit 900/min -j ACCEPT

ip6tables -A INPUT -p icmpv6 -j LOG
ip6tables -A INPUT -p icmpv6 -j DROP

ip6tables -A OUTPUT -p icmpv6 -j LOG
ip6tables -A OUTPUT -p icmpv6 -j DROP

ip6tables -A FORWARD -p icmpv6 -j LOG
ip6tables -A FORWARD -p icmpv6 -j DROP

# Block dst headers
ip6tables -A INPUT -m ipv6header --header dst -j REJECT
ip6tables -A OUTPUT -m ipv6header --header dst -j REJECT
ip6tables -A FORWARD -m ipv6header --header dst -j REJECT

# Block mobile IPv6
ip6tables -A INPUT --protocol mh -j REJECT
ip6tables -A OUTPUT --protocol mh -j REJECT
ip6tables -A FORWARD --protocol mh -j REJECT

# Allow local multicast
ip6tables -A INPUT -s ff00::/8 -j ACCEPT
ip6tables -A INPUT -d ff00::/8 -j ACCEPT

# Allow related and established connections. 
ip6tables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
ip6tables -A FORWARD -o eth0 -m state --state NEW -j ACCEPT
ip6tables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
ip6tables -A OUTPUT -p tcp -j ACCEPT
ip6tables -A OUTPUT -p udp -j ACCEPT



